### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by AggerTV** [drtshock/PlayerVaults#400]
### Idea
*Tell us what you want!*
I have translated the messages for you, from English to Danish.
https://pastebin.com/jt0fZfds

### Details
*Give some more information so we can get an idea.*
You could add the translation, so others can use it.

**Comment by CmdrKittens** [comment]
Thanks!

We have two additional translations if you're interested in adding them, otherwise for now they are starting as their English variants:
```
signs-disabled: "&cVault signs are currently disabled."
blocked-bad-item: "&cThis item is not allowed in a vault."
```

**Comment by CmdrKittens** [comment]
~~Deleted previous comment~~

Thanks for this! The file you sent does not quite match up with the current language, so I have updated it to remove two unused values and to add missing ones:

```yaml
# Use & for color codes.
# %p is where the player name will get inserted.
# %v is where the vault number will get inserted.
# %price is the price.
# %number is the vault number
# %converted is the number of vaults converted (where applicable)
# %m will be replaced by the blacklisted material (where applicable)
# Made with love :)

title-name: "&4[&fPlayerVaultsX&4]:"
open-vault: "&fÅbner vault &a%v"
open-other-vault: "&fÅbner vault &a%v &fof &a%p"
delete-vault: "&fSlettede vault &a%v"
delete-other-vault: "&fSlettede vault &a%v &fof &a%p"
delete-other-vault-all: "&4Deleted all vaults belonging to &a%p"
player-only: "&cUndskyld, men dette kan kun gøres af en spiller!"
must-be-number: "&cDu skal skrive et nummer mellem 1-99"
invalid-args: "&cUgyldige argumenter!"
no-permissions: "&cDu har ikke adgang til dette!"
insufficient-funds: "&cDu har ikke nok penge til dette!"
refund-amount: "&fDu blev tilbagebetalt &a%price &ffor sletning af vaulten."
cost-to-create: "&fDu betalte &c%price &ffor at lave vaulten."
cost-to-open: "&fDu betalte &c%price &ffor at åbne vaulten."
vault-title: "&4Vault #%number"
existing-vaults: "&f%p har vaults: &a%v"
no-owner-found: "&cKan ikke finde &a%p"
plugin-not-found: "&cKunne ikke konventere dette plugin."
conversion-complete: "&aKonventerede %converted players to PlayerVaults"
conversion-background: "&fKonventering er blevet kløvet til at køre i baggrunden. Se i konsolen for opdateringer."
vaults-locked: "&cVaults er i øjeblikket låst, imens konventeringen er iganværende. Prøv igen om lidt."
help: "/pv <number>"
blocked-item: "&6%m &cer blokeret fra vaults."
signs-disabled: "&cVault signs are currently disabled."
blocked-bad-item: "&cThis item is not allowed in a vault."
vault-does-not-exist: "&cThat vault does not exist!"
click-a-sign: "&fNow click a sign!"
not-a-sign: "&cYou must click a sign!"
set-sign-success: "&fYou have successfully set a PlayerVault access sign!"
open-with-sign: "&fOpening vault &a%v &fof &a%p"
```

If you are able to add those missing ones that would be awesome!
